//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hometask.DepositoBank.App.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hometask.DepositoBank.App.Properties.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter your balance (must be 0.01 or more):.
        /// </summary>
        internal static string EnterBalance {
            get {
                return ResourceManager.GetString("EnterBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ===Bank &quot;Deposito&quot;===
        ///
        ///Made by Anastasiia Atanasevych © Copyright 2024.
        ///.
        /// </summary>
        internal static string Greeting {
            get {
                return ResourceManager.GetString("Greeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are out of input attempts..
        /// </summary>
        internal static string NoAttemps {
            get {
                return ResourceManager.GetString("NoAttemps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These are our current rates:
        ///Rate S: from 0.01 to 99 - 5%
        ///Rate M: from 100 to 199 - 7%
        ///Rate L: from 200 - 10%..
        /// </summary>
        internal static string Rates {
            get {
                return ResourceManager.GetString("Rates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid balance: please, try to enter correct balance..
        /// </summary>
        internal static string WrongInput {
            get {
                return ResourceManager.GetString("WrongInput", resourceCulture);
            }
        }
    }
}
